In [1]:
print("Let's Start")

Let's Start

In [10]:
import pandas as pd

df1 = pd.read_csv('Books.csv')
df1 = df1.drop(columns=['Image-URL-S' , 'Image-URL-M' , 'Image-URL-L'])
df1.head()

C:\Users\Abhishek sharma\AppData\Local\Temp\ipykernel_33528\1893452743.py:3: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv('Books.csv')

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company

In [11]:
df2 = pd.read_csv('Ratings.csv')
df2.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [12]:
df3 = pd.read_csv('Users.csv')
df3.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [13]:
print(df1.shape)
print(df2.shape)
print(df3.shape)

(271360, 5)
(1149780, 3)
(278858, 3)

**popularity based rating system**

In [81]:
top_50 = df2[df2['Book-Rating'] == 10][:80]

In [82]:
isbn = top_50['ISBN'].to_list()

In [87]:
df = df1.merge(top_50 , on='ISBN')
df = df[:50]
df.shape

(50, 7)

In [89]:
df.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,User-ID,Book-Rating
0,0446310786,To Kill a Mockingbird,Harper Lee,1988,Little Brown &amp; Company,276953,10
1,0060930187,The Bell Jar : A Novel (Perennial Classics),Sylvia Plath,2000,Perennial,276986,10
2,0385720920,Choke,CHUCK PALAHNIUK,2002,Anchor,277051,10
3,0812550307,"The Fires of Heaven (The Wheel of Time, Book 5)",Robert Jordan,1994,Tor Fantasy,276964,10
4,081297106X,Reading Lolita in Tehran: A Memoir in Books,Azar Nafisi,2003,Random House Trade Paperbacks,277107,10

In [90]:
import pickle

pickle.dump(df , open('top_50_data' , 'wb'))